version: "3.5"

services:
  mysql:
    container_name: db
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: library_db
      MYSQL_ROOT_PASSWORD: password
    command: --character-set-server=utf8 --init_connect='SET collation_connection = utf8_unicode_ci' --collation-server=utf8_unicode_ci --skip-character-set-client-handshake --skip-name-resolve
    ports:
      - 6666:3306
